# Este archivo contiene las tareas para configurar port-security en un switch Cisco.
# Se utiliza el módulo `ios_config` para aplicar configuraciones específicas al puerto.

- name: Configurar port-security en el puerto
  ios_config:
    lines:
      - switchport mode access
      - switchport port-security
      - switchport port-security mac-address {{ mac_address }}
      - switchport port-security maximum 1
      - switchport port-security violation restrict
    parents: interface {{ interface_name }}