# Este playbook asigna una VLAN y configura port-security en un puerto específico
# basado en la dirección MAC proporcionada. Utiliza el role `switch_mac_control`.

- name: Asignar VLAN y port-security por MAC
  hosts: switches
  gather_facts: no
  vars:
    mac_address: "{{ mac_address }}"  # Dirección MAC del dispositivo.
    vlan_id: "{{ vlan_id }}"          # ID de la VLAN a asignar.
    interface_name: "{{ interface_name }}"  # Nombre del puerto en el switch.
  roles:
    - switch_mac_control