- name: Crear VLAN en el switch
  cisco.ios.ios_config:
    lines:
      - vlan {{ vlan.id }}
      - name {{ vlan.name }}

- name: Asignar puertos a VLAN
  cisco.ios.ios_config:
    lines:
      - interface {{ item }}
      - switchport mode access
      - switchport access vlan {{ vlan.id }}
    loop: "{{ vlan.access_ports }}"

- name: Configurar SVI
  cisco.ios.ios_config:
    lines:
      - interface Vlan{{ vlan.id }}
      - ipv6 address {{ vlan.vlan_ipv6_address }}/64
      - ipv6 nd managed-config-flag
      - ipv6 dhcp relay destination {{ router_ipv6 }}
      - no shutdown
