# Este playbook configura un switch Cisco para crear VLANs, asignar puertos de acceso y configurar DHCPv6 Relay.

- name: Crear VLANs en el switch
  ios_config:
    parents: vlan {{ item.id }}
    lines:
      - name {{ item.name }}
  loop: "{{ vlans }}"

- name: Asignar puertos de acceso a cada VLAN
  ios_config:
    parents: interface {{ item.1 }}
    lines:
      - switchport mode access
      - switchport access vlan {{ item.0.id }}
      - spanning-tree portfast
      - no shutdown
  loop: "{{ vlans | subelements('access_ports') }}"

- name: Configurar interfaz VLAN enrutada (SVI)
  ios_config:
    parents: interface Vlan{{ item.id }}
    lines:
      - ipv6 address {{ item.vlan_ipv6_address }}/64
      - ipv6 enable
      - ipv6 nd managed-config-flag
      - ipv6 dhcp relay destination {{ router_ipv6 }}
      - no shutdown
  loop: "{{ vlans }}"
